--EXEC sp_Util_Sort_DELETE 'tbTempSort',2
--EXEC sp_Util_Sort_UPDATE 'tbTempSort',1,'一级分类'
--EXEC sp_Util_Sort_MoveOrder 'tbTempSort',48,1
--EXEC sp_Util_Sort_INSERT 'tbTempSort',4,'C分类13'
--EXEC sp_Util_Sort_MoveSort 'tbTempSort',48,45
--EXEC sp_Util_Sort_SELECT 'SortID,SortName,SortParentID,SortParentPath,SortOrder','tbTempSort',0,1


EXEC sp_Util_Sort_INSERT 'tbTempSort', 0,'控制台根目录'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 1,'Microsoft SQL Servers'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 2,'SQL Server 组'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 2,'c组'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 3,'(LOCAL)(Windows NT)'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'数据库'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'数据转换服务'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'管理'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'复制'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'安全性'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'Meta Data Services'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 5,'支持服务'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 6,'master'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 6,'tempdb'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 13,'表'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'表'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'视图'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'关系图'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'存储过程'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'角色'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'用户'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'默认'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'用户自定义的数据'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 14,'用户自定义的函数'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 7,'本地包'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 7,'元数据'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 8,'备份'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 8,'Sql Server代理'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 8,'当前活动'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 8,'数据库维护计划'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 8,'sql server日志'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 9,'发布内容'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 9,'订阅'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 10,'登陆'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 10,'服务器角色'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 11,'contents'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 12,'sql邮件'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 12,'sql邮件2'
EXEC sp_Util_Sort_INSERT 'tbTempSort', 12,'sql邮件3'